# Site settings
title: 'Kevin Martins'
description: 'Web & Mobile App Developer'
url: 'https://KevinMartins367.github.io/'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'KevinMartins367'

author:
  name: 'Kevin Martins'
  email: kevincosta13679@outlook.com 
  facebook_username: KevinMartins367
  github_username:  KevinMartins367
  linkedin_username:  kevin-martins-010532119

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: :year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
